### ISSUE TITLE
license notice

### ISSUE THREAD

**Issue by jlovejoy** [tobiasahlin/SpinKit#102]
The MIT license requires including the copyright notice and license with the software, yet I don't see that included in the actual files.  Do you expect others to add it when they use your software? (or maybe you might want to add it, so it is always included :)

Thanks.

**Comment by tobiasahlin** [comment]
Hi @jlovejoy! The license file itself should be included, as it's part of the software. I noticed that the copyright year was outdated though, so took the time to update that. Thank you! :boom:
