### ISSUE TITLE
Table issue

### ISSUE THREAD

**Issue by maliyshock** [tobiasahlin/SpinKit#109]
http://codepen.io/anon/pen/epaNzg

Put your spinner into table and see this artefacts.

**Comment by tobiasahlin** [comment]
@maliyshock Thanks for reporting :pray: Not really sure what's going on here. This is 1) Not an issue in Safari (only Chrome), 2) much less prominent outside of codepen for me, and 3) something I was unable to fix by changing the `display` property for the container, or by playing around with adding transforms (e.g. `transform: translateY(0)` to any of the elements involved.

As far as I can tell, however, this is not an issue with SpinKit, but with how Chrome handles animations within tables, and how the spinner is being used. Closing for now.

**Comment by maliyshock** [comment]
http://codepen.io/anon/pen/epaNzgThis is working 23.11.2015, 18:02, "Tobias Ahlin" <notifications@github.com>:@maliyshock Thanks for reporting  Not really sure what's going on here. This is 1) Not an issue in Safari (only Chrome), 2) much less prominent outside of codepen for me, and 3) something I was unable to fix by changing the display property for the container, or by playing around with adding transforms (e.g. transform: translateY(0) to any of the elements involved.As far as I can tell, however, this is not an issue with SpinKit, but with how Chrome handles animations within tables, and how the spinner is being used. Closing for now.—Reply to this email directly or view it on GitHub.   _______________________________С уважением, Малышок Денис.Тел.: 8(953)342-89-65http://vkontakte.ru/id260319
