### ISSUE TITLE
how use set time finish loadpage

### ISSUE THREAD

**Issue by tuan-ph** [tobiasahlin/SpinKit#116]
hi,
i don't now finish loading page. help me.
please show code demo loadpage about 1s or 2s. 
Thank you!

**Comment by amiesak** [comment]
I don't know if I know what's on your mind but if You need to for example fade out preloader after page is loaded just use:

in html ( first spinner example )
`<div class="spinner"></div>`

and in js ( jQuery )
`$(window).on('load',function(){
   $('.spinner').fadeOut();
});`
