### ISSUE TITLE
Failed to resolve spinkit dependency

### ISSUE THREAD

**Issue by Swapnil-Garg16** [tobiasahlin/SpinKit#117]
failed to resolve compile 'com.github.ybq:Android-SpinKit:1.0.4'

**Comment by robbydp** [comment]
my problem too

**Comment by Leekao** [comment]
my problem three

**Comment by Nikhil-z** [comment]
Yeah i am also having same issue

**Comment by tobiasahlin** [comment]
That's an issue with https://github.com/ybq/Android-SpinKit - please report it there! 😃
