### ISSUE TITLE
How do I increase the size of the spinner ?

### ISSUE THREAD

**Issue by rajasimon** [tobiasahlin/SpinKit#118]
I tried to increase the width and height but that's not help me to increase the spinner.

**Comment by jmagnusson** [comment]
@rajasimon Try this PR https://github.com/tobiasahlin/SpinKit/pull/113

**Comment by soumak77** [comment]
@rajasimon I added scss mixins with PR #121, so you can customize the size to anything you want

**Comment by rajasimon** [comment]
Thanks
