### ISSUE TITLE
Add a background to the spinner that fades out with the spinner?

### ISSUE THREAD

**Issue by simpleidiot** [tobiasahlin/SpinKit#127]
Is this possible? I've been mucking around with jQuery and CSS for the last hour or two trying to figure this out, probably something really simple, lol.

**Comment by ATBO** [comment]
which spinner do you mean?
just define a background to the element the spinner depends on.
for example: 'rotating-plane' https://jsfiddle.net/y7yqusgr/
if you want to use the spinner as alpha mask, for example on the "cubemove" one, you could create svg masks and animate them with javascript.
there are some libs such as https://greensock.com/gsap to accomplish that.
i haven't found a way to animate svg mask using css only yet. don't even know if this is possible.
