### ISSUE TITLE
iOS Bug on 9-cube-grid

### ISSUE THREAD

**Issue by ATBO** [tobiasahlin/SpinKit#128]
iOS issue with animation-delay. see @ http://i.xomf.com/nhqkq.gif

**Comment by kurpav** [comment]
Any updates here?

**Comment by ATBO** [comment]
https://github.com/tobiasahlin/SpinKit/pull/129

**Comment by kurpav** [comment]
@ATBO thanks

**Comment by tobiasahlin** [comment]
Should be fixed in #143
