### ISSUE TITLE
sk-wave Issue with ReactJS. No spaces between vertical lines

### ISSUE THREAD

**Issue by nsainaney** [tobiasahlin/SpinKit#130]
<img width="74" alt="screen shot 2017-01-15 at 10 27 16 pm" src="https://cloud.githubusercontent.com/assets/306293/22053072/37683ca6-dd03-11e6-8329-21c005b905c3.png">

I have been wrestling with this for a while. Using a CSS diff tool and I can't find the difference between the sample code (using scss) and my project. Can anyone point me as to what might cause the sk-wave to squish like this?

I am using this in a ReactJS application. Interestingly, as soon as I put it in the react application jsx, I get this issue. Works fine when I have it in the app's container html. See below (html above, jsx below)

<img width="129" alt="screen shot 2017-01-17 at 11 03 32 pm" src="https://cloud.githubusercontent.com/assets/306293/22054216/438639ba-dd09-11e6-91cf-4da4515b4262.png">

**Comment by ATBO** [comment]
@nsainaney  u may use https://github.com/bentatum/better-react-spinkit for ur usecase.
according to the docs you can change gutter width and more easily. (http://better-react-spinkit.benjamintatum.com/#!/Wave)

**Comment by nsainaney** [comment]
Thanks!

**Comment by jjlorenzo** [comment]
I think this issue persists in this project, from my digging, if the html gets minified, the wave space is missing.

works
``` html
<div class="sk-wave">
    <div class="sk-rect sk-rect1"></div>
    <div class="sk-rect sk-rect2"></div>
    <div class="sk-rect sk-rect3"></div>
    <div class="sk-rect sk-rect4"></div>
    <div class="sk-rect sk-rect5"></div>
  </div>
```

does not work
``` html
<div class="sk-wave"><div class="sk-rect sk-rect1"></div><div class="sk-rect sk-rect2"></div><div class="sk-rect sk-rect3"></div><div class="sk-rect sk-rect4"></div><div class="sk-rect sk-rect5"></div></div>
```
