### ISSUE TITLE
Text/message

### ISSUE THREAD

**Issue by Vanuan** [tobiasahlin/SpinKit#131]
Is it possible to add a text message below the spinner?
Naive approach didn't work.

**Comment by ATBO** [comment]
what do you mean exactly?

you have every option html and css offers you. there is no "native" option given by SpinKit.
Here are two examples adding text below: https://jsfiddle.net/v02f6to7/
if you want the text also to be spinning or attached to the animation you first have to look at the animation css itself and decide if you add extra html / text in the spinner element itself or if pseudo elements are an option.

hope i could help you.
this isn't an issue, more an faq request. should be closed.

**Comment by Vanuan** [comment]
Thanks.
