### ISSUE TITLE
wave rely on spaces between rects elements

### ISSUE THREAD

**Issue by jjlorenzo** [tobiasahlin/SpinKit#139]
![bug](https://cloud.githubusercontent.com/assets/306293/22054216/438639ba-dd09-11e6-91cf-4da4515b4262.png)

If the html gets minified, the wave space is missing.

works
``` html
<div class="sk-wave">
    <div class="sk-rect sk-rect1"></div>
    <div class="sk-rect sk-rect2"></div>
    <div class="sk-rect sk-rect3"></div>
    <div class="sk-rect sk-rect4"></div>
    <div class="sk-rect sk-rect5"></div>
  </div>
```

does not work
``` html
<div class="sk-wave"><div class="sk-rect sk-rect1"></div><div class="sk-rect sk-rect2"></div><div class="sk-rect sk-rect3"></div><div class="sk-rect sk-rect4"></div><div class="sk-rect sk-rect5"></div></div>
```

**Comment by ATBO** [comment]
<script async src="//jsfiddle.net/wpcsbsma/embed/"></script>

**Comment by jjlorenzo** [comment]
Thanks!

I've read (but I don't remember where and I can't test right now) that in android browsers using `font-size:0` doesn't work.

My current fix is using `float: left`
```css
.sk-wave .sk-rect {
  float: left;
  margin-right: 1px;
}
```

Do you see any issue with my approach?

**Comment by ATBO** [comment]
i added a version of your approach in the jsfiddle.
https://jsfiddle.net/wpcsbsma/1/

no, this seems to be also a solution. 
and if you're right and there are problems with 0-font-size on android, your fix might be safer than the other approach. 

thanks for sharing your current fix 👍
