### ISSUE TITLE
[Quick Question] Is it possible to load this spinner only once at dash initialization?

### ISSUE THREAD

**Issue by NawalElBoghdady** [tobiasahlin/SpinKit#162]
I'm not sure if I can post this here, so if not allowed, please feel free to remove it. I was wondering if there is a way to load the spinner animation only once at the beginning of the dash figure initializations and not with every change that is made to the figures. I have figures updating every 10 minutes, so I was wondering if there is a way to specify that the spinner animation should be fired only once at the beginning.

There seems to be no solution to this currently.

Much appreciated!

**Comment by tobiasahlin** [comment]
Hey @NawalElBoghdady, this repo is only for the CSS that is driving these spinners, not the dash (?) implementation 👀 I'm not sure where that lives, and I'm not the author of it. Hope you can find it and find some guidance there!
