### ISSUE TITLE
4-wandering-cubes not following the pattern on Android Browser 4.1

### ISSUE THREAD

**Issue by GregOriol** [tobiasahlin/SpinKit#31]
It looks like the spinner 4-wandering-cubes is not following the designed pattern on Android Browser with Android 4.1 (maybe some others too) : instead of having the 2 cubes at opposite angles of a square share, they look like being at 2 consecutive angles. Do you have any idea on what might be going on ?

**Comment by seanfrasure** [comment]
Browser is supposedly just like IE. IE does not work very well with code, its really buggy.
