### ISSUE TITLE
New animation: "Unfolding"

### ISSUE THREAD

**Issue by macu** [tobiasahlin/SpinKit#48]
I love your style so I'm thinking of a little commission.

The three bounce is perfect for route transitions, but there are moments in certain views where a component is only fully constructed on demand. Suppose it takes a few seconds, up to six in my case, to build the component; I would like to overlay a spinner that conveys the work of "unboxing" (which the user prefers over "construction" in data entry apps).

The animation would begin with a plain square that unfolds from the centre into a diamond, which then unfolds from the centre into a square. If possible the shape would continuously shrink, and the shape would always be the same size, but if that's too difficult then the larger diamond could scale down before unfolding, and the larger square could scale down before the animation repeated. A simpler version of all this is to simply rotate the diamond back to the square and repeat, but I think the full version is more compelling.

This (or something like it) would make a nice addition to the SpinKit collection :D

![unboxing](https://cloud.githubusercontent.com/assets/889388/3495941/57c6e4e8-05dd-11e4-85b5-09cfbcbcd3d6.png)

**Comment by tobiasahlin** [comment]
Aiming to have this done by Tuesday (just updated the 2.0 milestone), will send you a preview when I have one ready :bow:

**Comment by tobiasahlin** [comment]
@macu So, I ended up with this: https://github.com/tobiasahlin/SpinKit/pull/87 - it's quite far from your original proposal, but this is where inspiration took me :smiley: Might have another go at this sometime, but closing the issue for now :heart: thanks for the detailed post, and the inspiration!

**Comment by macu** [comment]
Very nice!
