### ISSUE TITLE
Add a fallback spinner for browsers that don't support CSS animations

### ISSUE THREAD

**Issue by tobiasahlin** [tobiasahlin/SpinKit#59]
Let's make it easier to drop a sk-spinner into your project. You shouldn't have to implement this yourself.

**Comment by AlexRebula** [comment]
Hey guys. Thank you for this lovely CSS kit. I have question though. About the fallback for older browsers you mention in the readme file at the bottom. Are you sure checking just for the 'animation' property is enough for the checkup to be reliable? Please, see [this thread](https://github.com/joaopereirawd/fakeLoader.js/issues/5) to find out why I am asking that. Thanks.

**Comment by tobiasahlin** [comment]
@jmagnusson @rkorebrits Good point, killing this for now :fire:

@AlexRebula afaik that should be enough, hope you got it to work eventually!
