### ISSUE TITLE
Spinning square animation bug

### ISSUE THREAD

**Issue by julianxhokaxhiu** [tobiasahlin/SpinKit#65]
Just go the next slide (circle) and go back to previous one (square).

You'll see that the square is not animating anymore. But if you inspect the item you'll see that the div is "rotating" but not repainting.

A bug?

Tested on Chrome 38.0.2125.122 (Build 290379) m 64bit

**Comment by Invulner** [comment]
Looks like visibility property for '#spinners li' connected with this issue. It works fine after removing this property from code. I know that switching between visibility's values cause repaint, but I can't explain why it's so important only for the first slide only. And I see that it's not connected with type of animation. We can put any of them to the first slide and it won't work too.

**Comment by tobiasahlin** [comment]
@Invulner Thanks for investigating! Would you mind opening a PR? :heart:

**Comment by tobiasahlin** [comment]
Fixed this in #86 with the fix that @Invulner suggested (thanks! :heart:)
