### ISSUE TITLE
Demo different than the examples.

### ISSUE THREAD

**Issue by KatelynL** [tobiasahlin/SpinKit#78]
Why are the spinners on the demo site vastly different than the examples. In particular the circle spinner on the demo has fewer dots in the spinner and the source is very different than the code in the examples/8-circle.html.  And the css for the circle spinner on the demo page is not spinkit.css file.  Can the example files be updated to include the exact spinners on the demo page? 

Thanks.

**Comment by alexg313** [comment]
Just came across this difference as well.

**Comment by tobiasahlin** [comment]
Will have a look, thanks @KatelynL and @alexg313!

(Possibly something that happened in the move to sass @jmagnusson?)

**Comment by jmagnusson** [comment]
Thanks for the report you guys.

I'm super busy these days though... do you think you can take a look at it @tobiasahlin?

**Comment by tobiasahlin** [comment]
@jmagnusson Will do! :heart::boom:

**Comment by DanielRuf** [comment]
Still different for the `rectangle-bounce` example. Different class names, sizes, missing margins, ...
