### ISSUE TITLE
Register to NPM

### ISSUE THREAD

**Issue by jmagnusson** [tobiasahlin/SpinKit#81]
Would be nice to be able to `npm install -D spinkit` like with Bower. I could publish it myself, but perhaps it would look better if we had an official npm account for SpinKit?

**Comment by jmagnusson** [comment]
What's your thoughts @tobiasahlin?

**Comment by jmagnusson** [comment]
Ping @tobiasahlin :wink:

**Comment by tobiasahlin** [comment]
@jmagnusson On it! :heart:

**Comment by jmagnusson** [comment]
Sweet! :smiley:

**Comment by tobiasahlin** [comment]
https://www.npmjs.com/package/spinkit :tada:

**Comment by jmagnusson** [comment]
:dancer: :confetti_ball:
