### ISSUE TITLE
Conflict with Animate.css plugin

### ISSUE THREAD

**Issue by dfabreguette-ap** [tobiasahlin/SpinKit#83]
Hi,
I just stumbled upon a conflict using Animate CSS “plugin" (https://daneden.github.io/animate.css/), looks like they have keyframes called as well "bounce".
Maybe it would be better if spinKit keyframes have a specfic prefix like "spinKitBounce", it would avoid such conflicts as "bounce" is pretty common for CSS animation name...
Thank you anyway for this great work :+1:

**Comment by bluedaniel** [comment]
+1

**Comment by jmagnusson** [comment]
What version are you using and where did you get it from?
Every css and `@keyframes` rule has been prefixed with `sk-` for quite some time now.

**Comment by dfabreguette-ap** [comment]
![image](https://cloud.githubusercontent.com/assets/7055931/8646547/0d5704ea-2951-11e5-9179-91f633bd9fd2.png)
I took source code from http://tobiasahlin.com/spinkit/ . Don't know about the version though.

**Comment by tobiasahlin** [comment]
![omg](https://cloud.githubusercontent.com/assets/211284/8650071/4a8ff1f4-2970-11e5-8838-0879d00b3cc1.gif)


@dfabreguette-ap Have to manually update the showcase, I'm on it, thanks!

**Comment by jmagnusson** [comment]
@tobiasahlin To avoid this kind of problem in the future we could perhaps integrate the demo site within this repo. Feels a bit unnecessary to have both the examples folder with html examples, and your separate examples web page.

**Comment by dfabreguette-ap** [comment]
No problemo :)

**Comment by jmagnusson** [comment]
@dfabreguette-ap For now if you want the latest code [you can download the code from the Releases section](https://github.com/tobiasahlin/SpinKit/releases), or in a more automated way through [Bower](http://bower.io/).

**Comment by tobiasahlin** [comment]
@jmagnusson Agree, shouldn't really be any conflicts between these two. Will see if I can just pull this repo into the demo page. 

(If we should remove anything though, we should kill the examples in this repo, since the demo page is driving a lot of traffic to the repo (if you look under https://github.com/tobiasahlin/SpinKit/graphs/traffic) - I'm all for doing that!)

**Comment by jmagnusson** [comment]
That would be awesome :facepunch: 
Demo page over examples folder any day!
