### ISSUE TITLE
package.json breaks npm import with Browserify

### ISSUE THREAD

**Issue by strom** [tobiasahlin/SpinKit#96]
The current `main` is the gulpfile. However, there are dependencies specified as devDependencies, which breaks Browserify's bundle function because it can't find modules that are required.

I believe the solution should be to remove `gulpfile.js` as the main file in package.json, because users aren't going to use the gulpfile from this project outside of developing.

**Comment by tobiasahlin** [comment]
@strom Thanks for reporting! :bow::heart:

> I believe the solution should be to remove `gulpfile.js` as the main file in package.json, because users aren't going to use the gulpfile from this project outside of developing.

Sounds fair. @jmagnusson thoughts?
